### PR TITLE
fix: convert lists to sets

### LINKED ISSUE #16: API returns data in a different order, so terraform sees a meaningless change?
Hello conduktor team,

I tried the provider and have the following user setup.

```hcl
resource "conduktor_user_v2" "user" {
  name     = "first.name@somedomain.com"
  spec {
    firstname = "firstname"
    lastname  = "name"
    permissions = [
      {
        resource_type = "TOPIC"
        name          = "a-topic"
        cluster       = "test"
        pattern_type  = "PREFIXED"
        permissions   = local.topic_read_permissions
      },
      {
        resource_type = "TOPIC"
        name          = "b-topic"
        cluster       = "test"
        pattern_type  = "PREFIXED"
        permissions   = local.topic_read_permissions
      },
      {
        resource_type = "TOPIC"
        name          = "c-topic"
        cluster       = "test"
        pattern_type  = "PREFIXED"
        permissions   = local.topic_read_permissions
      }
    ]
  }
}
```

The first apply is fine. Now I'm doing a terraform plan and get following plan
```hcl
  # conduktor_user_v2.user will be updated in-place
  ~ resource "conduktor_user_v2" "user" {
        name = "first.name@somedomain.com"

      ~ spec {
          ~ permissions = [
              ~ {
                  ~ name          = "c-topic" -> "b-topic"
                    # (4 unchanged attributes hidden)
                },
              ~ {
                  ~ name          = "b-topic" -> "c-topic"
                    # (4 unchanged attributes hidden)
                },
                # (1 unchanged element hidden)
            ]
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I changed nothing and the user was not touched.

### PR DESCRIPTION
**Pull request by marnas**
Considering console API returns lists in an unpredictable order and causing unwanted plan changes, the following list attributes have been updated into Set / SetNested. Resolves #16
- user_v2 resource
```
/spec/permissions
/spec/permissions/permissions
```

- group_v2 resource
```
/spec/members
/spec/members_from_external_groups
/spec/external_groups
/spec/permissions
/spec/permissions/permissions
```

Tests updated accordingly

### CODE REVIEW

File: internal/test/test_helpers.go [hunk 1]
```diff
@@ -73,3 +84,146 @@ func TestAccPreCheck(t *testing.T) {
...
+					Permissions:  flags,
+					PatternType:  p.PatternType.ValueString(),
+					Cluster:      p.Cluster.ValueString(),
+					KafkaConnect: p.KafkaConnect.ValueString(),
+				})
+			}
+		}
+	}
+	return permissions, nil
+}
```
Comment (qboileau) [inline internal/test/test_helpers.go:229]: Instead of those function in test_helpers, we already have a internal/schema/schema_utils.go that contain a bunch of utility function used in mapping to and from terraform schema types

File: internal/test/test_helpers.go [hunk 2]
```diff
@@ -73,3 +84,146 @@ func TestAccPreCheck(t *testing.T) {
...
+
+	if diag.HasError() {
+		return basetypes.SetValue{}, mapper.WrapDiagError(diag, "permissions", mapper.FromTerraform)
+	}
+
+	return permissionsList, nil
+}
+
+// Parse a Set into an array of Permissions based on resource type.
+func SetValueToPermissionArray(ctx context.Context, resource string, set basetypes.SetValue) ([]model.Permission, error) {
```
Comment (qboileau) [inline internal/test/test_helpers.go:172]: Instead of a "magic string" for the resource type, it would be better to define and use an enum for this (same apply in `PermissionArrayToSetValue`)

File: internal/provider/group_v2_resource_test.go [hunk 3]
```diff
@@ -53,13 +53,13 @@ func TestAccGroupV2Resource(t *testing.T) {
...
-					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.1.cluster", "*"),
-					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.1.pattern_type", "LITERAL"),
-					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.1.permissions.#", "3"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.0.resource_type", "TOPIC"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.0.name", "test-topic"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.0.cluster", "*"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.0.pattern_type", "LITERAL"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.0.permissions.#", "3"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.1.resource_type", "PLATFORM"),
+					resource.TestCheckResourceAttr(resourceRef, "spec.permissions.1.permissions.#", "4"),
```
Comment (qboileau) [inline internal/provider/group_v2_resource_test.go:62]: so order in tests is consistent ?

File: internal/mapper/user_v2/user_v2_resource_mapper.go [hunk 4]
```diff
@@ -7,37 +7,22 @@ import (
...
-				PatternType:  p.PatternType.ValueString(),
-				Cluster:      p.Cluster.ValueString(),
-				KafkaConnect: p.KafkaConnect.ValueString(),
-			})
-		}
+	if r.Spec.Permissions.IsNull() {
+		tflog.Debug(ctx, "ListValue externalGroups is null")
+	} else if r.Spec.Permissions.IsUnknown() {
+		tflog.Debug(ctx, "ListValue externalGroups is unknown")
+	}
```
Comment (qboileau) [inline internal/mapper/user_v2/user_v2_resource_mapper.go:22]: could move the logs in SetValueToPermissionArray maybe. (not sure this logs are actually useful btw)

File: internal/provider/group_v2_resource_test.go (hunk 3 above)
Comment (marnas) [reply internal/provider/group_v2_resource_test.go:62]: yes, it has been with all the tests I've ran during development

File: internal/mapper/user_v2/user_v2_resource_mapper.go (hunk 4 above)
Comment (marnas) [reply internal/mapper/user_v2/user_v2_resource_mapper.go:22]: I'm happy to remove those to be fair, I was just replicating a pattern I've seen for the `ExternalGroups` but I'm also unsure about the actual value

File: internal/test/test_helpers.go (hunk 1 above)
Comment (marnas) [reply internal/test/test_helpers.go:229]: I will move them into `schema_utils.go` and delete the duplicate helpers functions - totally missed that!

File: internal/mapper/user_v2/user_v2_resource_mapper.go (hunk 4 above)
Comment (qboileau) [reply internal/mapper/user_v2/user_v2_resource_mapper.go]: I think I've put them at some point to debug weird behavior on list, but it ends up being fixed by a framework codegen update. So feel free to remove them

Comment (marnas) [reply internal/mapper/user_v2/user_v2_resource_mapper.go]: Done ✅

**Review by qboileau — APPROVED** [review]
